language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - DJANGO_VERSION=1.4.15
  - DJANGO_VERSION=1.5.10
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.15
    - python: "2.6"
      env: DJANGO_VERSION=1.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION towel==0.3.1 --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
